version: '3.8'

services:
  dns-filter:
    build: .
    container_name: dns-filter
    ports:
      - "5000:5000"    # Web dashboard
      - "5353:5353/udp" # DNS server
    volumes:
      - ./config.json:/app/config.json
      - ./blocklists:/app/blocklists
      - dns_filter_data:/app/data
    environment:
      - DNS_FILTER_HOST=0.0.0.0
      - DNS_FILTER_PORT=5353
      - DNS_FILTER_WEB_PORT=5000
    restart: unless-stopped
    networks:
      - dns-filter-network

  # Optional: Nginx reverse proxy for HTTPS
  nginx:
    image: nginx:alpine
    container_name: dns-filter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - dns-filter
    networks:
      - dns-filter-network
    profiles:
      - proxy

volumes:
  dns_filter_data:

networks:
  dns-filter-network:
    driver: bridge