[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dnslib>=0.9.26",
    "flask>=3.1.1",
    "requests>=2.32.3",
]
